import React, { useLayoutEffect, useMemo, useRef } from 'react';
import {
    Audio,
    continueRender,
    delayRender,
    Sequence,
    Series,
    staticFile,
    useCurrentFrame,
    useVideoConfig,
} from 'remotion';

/**
 * Plays the design page's frames (HTML generated by each video's design.js, see market-signings/build.mjs) frame-exactly:
 * every CSS animation is paused and seeked to the current time (animation-delay = its --d − t), and the
 * rolling counters ([data-to]) are recomputed for each frame, so the render matches the approved mock.
 */
export interface HtmlVideoSpec {
    date: string;
    css: string;
    frames: { n: string; dur: number; kind?: ScreenKind; html: string }[];
}

/** What a screen is in every story video: the opening, one item (player…) or the brand close. Drives the sound effects. */
export type ScreenKind = 'intro' | 'player' | 'outro';

/**
 * Sound effects per screen kind (public/sfx), the same in every video. Offsets measured on the waveforms (RMS in 20 ms windows):
 * - intro-riser.mp3 (4.03 s, fits the 5 s intro): builds from silence, loudest ≈ 2.9 s and cuts dead at 3.70 s (its culmination). The cover's headline
 *   lands at t ≈ 0 (the 0-signings headline at ≈ 1–1.9 s), so it can't culminate on it: it starts at t = 0 and culminates at 3.70 s.
 * - player-whoosh.mp3 («Swoosh 015», 1.06 s): audible from ≈ 0.30 s, peak 0.42–0.50 s. The cut-out player blurs in at --d .05 s
 *   over 1.3 s (cubic-bezier(.16,1,.3,1): 80 % visible at 0.35 s), so the first 0.1 s of the file is trimmed: peak at ≈ 0.32–0.40 s.
 * - outro-boom.mp3 (2.09 s): silent for 70 ms, then the hit (loudest ≈ 0.34 s). The crest starts at --d .1 s → start at frame 1
 *   (33 ms) so the hit lands at 0.10 s, with the crest, and the body peaks as it becomes 80 % visible (0.40 s).
 * Volumes, checked on the rendered mix (sample peak and RMS in 20 ms windows): riser 0.5 (plateau ≈ −12 dB RMS), boom 0.85
 * (≈ −12 dB RMS, peak ≈ −2 dBFS), whoosh 0.9 (≈ −15 dB RMS: a bit under the boom); nothing reaches 0 dBFS.
 */
const SFX: Record<
    ScreenKind,
    { file: string; from: number; trim?: number; volume: number }
> = {
    intro: { file: 'sfx/intro-riser.mp3', from: 0, volume: 0.5 },
    player: { file: 'sfx/player-whoosh.mp3', from: 0, trim: 0.1, volume: 0.9 },
    outro: { file: 'sfx/outro-boom.mp3', from: 1 / 30, volume: 0.85 },
};

function ScreenSfx({ kind }: { kind?: ScreenKind }) {
    const { fps } = useVideoConfig();

    if (!kind) {
        return null;
    }

    const sfx = SFX[kind];

    return (
        <Sequence
            from={Math.round(sfx.from * fps)}
            name={'sfx ' + kind}
            layout="none"
        >
            <Audio
                src={staticFile(sfx.file)}
                trimBefore={sfx.trim ? Math.round(sfx.trim * fps) : undefined}
                volume={sfx.volume}
            />
        </Sequence>
    );
}

export const htmlVideoFrames = (spec: HtmlVideoSpec, fps: number) =>
    spec.frames.reduce((s, f) => s + Math.round(f.dur * fps), 0);

/* CSS animations driven by Remotion's clock instead of the wall clock */
const DRIVER_CSS = `
.remo-frame *, .remo-frame *::before, .remo-frame *::after {
  animation-play-state: paused !important;
  animation-delay: calc(var(--d, 0s) - var(--t)) !important;
}
.remo-frame .fr { position: absolute; left: 0; top: 0; }
`;

/* same formats as core.js fmtC */
const es = (n: number, dd = 0) =>
    n.toLocaleString('es-ES', {
        minimumFractionDigits: dd,
        maximumFractionDigits: dd,
        useGrouping: 'always',
    } as unknown as Intl.NumberFormatOptions);
function fmtC(v: number, f: string): string {
    const MM = (n: number, dd = 1) => es(n / 1e6, dd) + ' M€';

    if (f === 'e') {
        return es(Math.round(v)) + ' €';
    }

    if (f === 'm') {
        return MM(v);
    }

    if (f === 'm0') {
        return MM(v, 0);
    }

    if (f === 'm2') {
        return MM(v, 2);
    }

    if (f === 'd1') {
        return es(v, 1);
    }

    if (f === 'd2') {
        return es(v, 2);
    }

    if (f === 's') {
        return (v > 0 ? '+' : v < 0 ? '−' : '') + es(Math.abs(Math.round(v)));
    }

    if (f === 'sm') {
        return (v > 0 ? '+' : v < 0 ? '−' : '') + MM(Math.abs(v));
    }

    if (f === 'pct') {
        return es(Math.round(v)) + '%';
    }

    return es(Math.round(v));
}

function HtmlFrame({ html }: { html: string }) {
    const frame = useCurrentFrame();
    const { fps } = useVideoConfig();
    const t = frame / fps;
    const ref = useRef<HTMLDivElement>(null);
    /* app URLs → files copied into public/mk by each video's build.mjs; the frame replays from its start like the mock's .run */
    const markup = useMemo(
        () =>
            html
                .replaceAll(
                    'src="/storage/',
                    `src="${staticFile('mk/storage/')}`,
                )
                .replaceAll('src="/images/', `src="${staticFile('mk/images/')}`)
                .replace('<div class="fr"', '<div class="fr run a-crt"'),
        [html],
    );

    /* wait for every image of this frame before the first screenshot */
    useLayoutEffect(() => {
        const imgs = Array.from(
            ref.current?.querySelectorAll('img') ?? [],
        ).filter((img) => !img.complete);

        if (imgs.length === 0) {
            return;
        }

        const handle = delayRender('frame images');
        Promise.all(
            imgs.map(
                (img) =>
                    new Promise((res) => {
                        img.onload = res;
                        img.onerror = res;
                    }),
            ),
        ).then(() => continueRender(handle));
    }, [markup]);

    /* rolling counters, exactly like the mock's runCounters (start = host --d + 150 ms, ease-out cubic) */
    useLayoutEffect(() => {
        ref.current
            ?.querySelectorAll<HTMLElement>('[data-to]')
            .forEach((el) => {
                const to = Number(el.dataset.to),
                    from = Number(el.dataset.from || 0),
                    f = el.dataset.f ?? 'int',
                    dur = Number(el.dataset.dur || 900) / 1000;
                const lead = Number(el.dataset.lead ?? 0.15);
                const host = el.closest<HTMLElement>('[style*="--d"]');
                const dl =
                    el.dataset.dl != null
                        ? Number(el.dataset.dl)
                        : host
                          ? parseFloat(
                                getComputedStyle(host).getPropertyValue('--d'),
                            ) || 0
                          : 0;
                const p = Math.max(0, Math.min(1, (t - dl - lead) / dur));
                el.textContent = fmtC(
                    from + (to - from) * (1 - Math.pow(1 - p, 3)),
                    f,
                );
            });
    });

    return (
        <div
            ref={ref}
            className="remo-frame"
            style={{
                position: 'absolute',
                inset: 0,
                ['--t' as string]: `${t}s`,
            }}
            dangerouslySetInnerHTML={{ __html: markup }}
        />
    );
}

export function HtmlVideo({ spec }: { spec: HtmlVideoSpec }) {
    const { fps } = useVideoConfig();

    return (
        <div className="stagezoom">
            <style>{spec.css + DRIVER_CSS}</style>
            <Series>
                {spec.frames.map((f, i) => (
                    <Series.Sequence
                        key={i}
                        durationInFrames={Math.round(f.dur * fps)}
                        name={f.n}
                    >
                        <HtmlFrame html={f.html} />
                        <ScreenSfx kind={f.kind} />
                    </Series.Sequence>
                ))}
            </Series>
        </div>
    );
}

/** One screen alone, for review stills. */
export function HtmlScreen({
    spec,
    index,
}: {
    spec: HtmlVideoSpec;
    index: number;
}) {
    return (
        <div className="stagezoom">
            <style>{spec.css + DRIVER_CSS}</style>
            <HtmlFrame html={spec.frames[index].html} />
        </div>
    );
}
